### ISSUE TITLE
Bug: Input Field Does Not Display Typed Text

### ISSUE THREAD

**Issue by Philomath88** [suitedaces/computer-agent#5]
Description:
When running the computer-agent project, text typed into the input field does not appear. Key presses are registered, but the input_area does not display any text, resulting in an unusable input field.

Steps to Reproduce:

Clone the repository and set up the environment as described in the README.
Run the application using python run.py.
Attempt to type into the input field.
Expected Behavior:
Text should appear in the input field as it is typed.

Observed Behavior:
Key presses are detected, but no text is displayed in the input_area.

Cause:
The issue is caused by the custom keyPressEvent handler in window.py, which overrides the default handling for QTextEdit. Commenting out the following line allows the input field to function as expected:

python
Copy code
# self.input_area.keyPressEvent = self.handle_input_keypress
Workaround: Commenting out or removing the line above restores normal text display in the input field.

Suggested Fix: Review and potentially refactor handle_input_keypress to avoid overriding default text handling in QTextEdit, or add conditions to selectively process only specific key events without affecting general text input.

System Information:

Device: MacBook Pro M2
macOS Version: 15.0.1 (24A348)
Python version: 3.x
PyQt version: [Specify if known]
Additional Notes:
This fix may require additional review to ensure that other key press functionalities (such as shortcuts) are not affected.

**Comment by suitedaces** [comment]
Pushing a fix for this today! Introduced this in my previous commit :p

**Comment by suitedaces** [comment]
https://github.com/suitedaces/computer-agent/commit/82c0d9fe8bbabf242cd4313fbfa51a9e294bd941

Fixed!

**Comment by suitedaces** [comment]
@Philomath88 lmk if it worked for you?

**Comment by Philomath88** [comment]
@suitedaces Amazingly fast response! This works!
