### ISSUE TITLE
Application Not Shutting Down Properly on macOS

### ISSUE THREAD

**Issue by Philomath88** [suitedaces/computer-agent#6]
@suitedaces since you responded so fast... :) 

Description
The Python application cannot be terminated properly through normal means. The application window remains open and processes continue running even after attempting various shutdown methods.
Current Behavior

Ctrl+C does not terminate the application
Ctrl+Z suspends the process but UI window remains open
Force Quit via macOS shows multiple Python processes
Previous cleanup implementations including os._exit(0) and atexit handlers do not successfully terminate the application
Terminal shows IMKInputSession messages and hangs

Error Messages
Copy2024-11-08 00:23:31,637 - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2024-11-08 00:23:31,638 - DEBUG - load_verify_locations cafile='/Users/maximilliandoelle/Projects/computer-agent/venv/lib/python3.10/site-packages/c'
2024-11-08 00:23:31,644 - DEBUG - load_verify_locations cafile='/Users/maximilliandoelle/Projects/computer-agent/venv/lib/python3.10/site-packages/c'
2024-11-08 00:23:32,278 python[55564:12121803] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
^C^C^C^Z
zsh: suspended python run.py
Steps to Reproduce

Run the application using python run.py
Attempt to close the application using:

Close button
Ctrl+C
Ctrl+Z
Force Quit

Observe that application processes remain running

Environment

Operating System: macOS Sonoma 15.0.1 (24A348)
Hardware: MacBook Pro 16-inch, 2023
Processor: Apple M2 Max
Memory: 96 GB
Python Version: 3.10
PyQt Version: 6
Running in virtual environment (venv)

Attempted Solutions
The following solutions have been tried without success:

Implementing closeEvent with event.accept()
Using QApplication.quit()
Using os._exit(0)
Implementing cleanup with atexit
Adding signal handlers for SIGINT
Force Quit via macOS Activity Monitor

Possible Related Issues

Multiple Python processes being spawned
PyQt event loop not properly terminating
IMKInputSession causing interference with normal shutdown (may be specific to macOS Sonoma)
Background threads potentially preventing clean shutdown

Additional Notes

The application creates multiple Python processes that remain active
Force Quit via macOS Activity Monitor shows these processes need to be terminated individually
The IMKInputSession messages suggest potential macOS-specific input handling issues
This issue is occurring on the latest macOS Sonoma version, which might indicate a compatibility issue with the new OS

Questions for Investigation

Are there any background threads that need explicit cleanup?
Is there a race condition in the shutdown process?
Could the IMKInputSession be interfering with normal shutdown procedures specifically on macOS Sonoma?
Are there any PyQt-specific shutdown handlers that need to be implemented for Apple Silicon Macs?
Is this a known issue with PyQt6 on macOS Sonoma?

**Comment by Philomath88** [comment]
**Update**

I know I should read... Ctrl + Q works... it's just weird when I playing around with the code that Ctrl + c or Ctrl + Z does not properly close it... 

Feel free to disregard close...

**Comment by suitedaces** [comment]
@Philomath88 yep, Ctrl+Q should work! I know it takes a bit for Ctrl+C to end the agent action.. lmk if you have any specific keybinding suggestions you'd like to see
